PYTHONTOLUA = 0
PYTHONISLEM = ""

MESSAGE_MESAJLAR = []
MESSAGE_TOPLAM = 0
MESSAGE_MESAJ = ""
MESSAGE_MESAJ2 = ""
MESSAGE_GONDERILEN = ""
MESSAGE_NAME = ""
MESSAGE_ACIK = 0

WHISPER_GORULDU_LIST = []
WHISPER_GORULDU_TIME_LIST = {}
WHISPER_GET = 0 #1: kapalý mesaj için, 2:lv,açýk durumunu almak için --- (pm'yi açtýðý vakit baðlý deðil yazýsýný engellemek için)
WHISPER_SECILEN = ""
WHISPER_LEVEL = {}
WHISPER_ENGEL = {}
WHISPER_OTO_MESAJ = 0
WHISPER_OTO_MESAJ_TEXT = ""
WHISPER_YOLLANANLAR = []
WHISPER_TARIH_AD = []